openapi: 3.0.1
info:
  title: cartApi
  description: API Definition of cartApi
  version: 1.0.0
servers:
- url: http://localhost:8290/cart
paths:
  /{sellerId}:
    get:
      parameters:
      - name: sellerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /sendSMS:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  validateOTP:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
